stock_app:
    url: "https://robot-dreams-de-api.herokuapp.com"
    auth_endpoint: "/auth"
    data_endpoint: "/out_of_stock"

currency_app:
    url: "http://api.exchangeratesapi.io/v1/latest"
    symbols:
        - 'GBP'
        - 'ABC'
        - 'UAH'
        - 'USD'

app2:
    test: 1