stock_app:
    url: "https://robot-dreams-de-api.herokuapp.com"
    auth_endpoint: "/auth"
    data_endpoint: "/out_of_stock"
    username: "rd_dreams"
    password: "djT6LasE"
    directory: '/home/user/stock_api/'

pg_creds:
    host: "localhost"
    port: "5432"
    database: "dshop"
    user: "pguser"
    password: "secret"

hdfs_creds:
    host: "http://127.0.0.1:50070/"
    user: "user"
    password: "user"

currency_app:
    url: "http://api.exchangeratesapi.io/v1/latest"
    access_key: "eca151fb6fb85f62966f98e8f8b5200b"
    symbols:
        - 'GBP'
        - 'ABC'
        - 'UAH'
        - 'USD'
    directory: 'C:\Users\odejkun\currency\'

app2:
    test: 1